import "./style.css";
import Sidebar from "@/components/Sidebar";

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`container`}>
        <div className="main">
          <Sidebar></Sidebar>
          <section className="col note-viewer">{children}</section>
        </div>
      </body>
    </html>
  );
}
